### ISSUE TITLE
Can't connect to MAL or to Hummingbird

### ISSUE THREAD

**Issue by bjk14** [arkenthera/Chiika#25]
I'm using windows 10, when I try to login in MAL the borders become red,
when I try in Hummingbird the program close.

Here the logs I found on (C:\Users\Esaú\AppData\Roaming\chiika)
They say at end "Request returned successful but the status code is 403/301"

[chiika MAL.txt](https://github.com/arkenthera/Chiika/files/938886/chiika.MAL.txt)
[chiika HUM.txt](https://github.com/arkenthera/Chiika/files/938887/chiika.HUM.txt)

**Comment by 0x61726b** [comment]
Hey, thanks for your interest. Unfortunately, Chiika development has stopped and is unlikely to continue in the future. That being said, I remember MAL api being changed so probably thats why it returns 403.

**Comment by wopian** [comment]
Try https://github.com/erengy/taiga which is under active development and supports MAL & Kitsu* (Hummingbird)

\* Currently only available with the [1.3.0 alpha](http://taiga.moe/latest.html)
