### ISSUE TITLE
Not start

### ISSUE THREAD

**Issue by Watashis** [arkenthera/Chiika#27]
Sorry for English (I use online translator).
I do not work this program.
I cannot use npm/nodejs. installed everything with `sudo sh command travis-build.sh`  and started with ` npm start`  but nothing started
![image](https://user-images.githubusercontent.com/22397077/49455460-ac58f680-f800-11e8-8168-268d0c0f5145.png)
![image](https://user-images.githubusercontent.com/22397077/49455550-ceeb0f80-f800-11e8-8f26-ce7496bc55d4.png)

[npm-debug.log](https://github.com/arkenthera/Chiika/files/2644812/npm-debug.log)

**Comment by j-heavy** [comment]
What directory are you running in?

**Comment by Watashis** [comment]
> What directory are you running in?

/home/vladislav/github/Chiika

**Comment by j-heavy** [comment]
Did you use ```npm i``` before starting and others command required to run?

**Comment by 0x61726b** [comment]
Hey, this project is dead :/ Also myanimelist API is also dead so the app wouldnt work anyway

**Comment by j-heavy** [comment]
@arkenthera okay, thanks
U can close this issue
